Add cloudcustodian
18F/aws-admin pull request #77
Opened 2020-08-06 21:16 UTC by JJediny

Adds running `inventory` rules for simple auditing and adds curated draft rules for decision and ultimate editing/deletion.

2020-08-13 20:26 UTC, afeld commented on .circleci/config.yml
> +    - build
Let's enable CircleCI and make sure this works! Please be sure to turn off public access so we don't accidentally leak any keys or anything.

2020-08-13 20:26 UTC, afeld commented on .gitignore
> +*/output
Minor: The `*/` is implicit anyway.

2020-08-13 20:27 UTC, afeld commented on custodian/DRAFT.md
> +## Cloud Custodian Policies
Are we still using this file?

2020-08-13 20:31 UTC, afeld commented on custodian/accounts.yml
> +accounts:
We should look into generating this file programmatically. Not a blocker.

2020-08-13 20:31 UTC, afeld commented on custodian/Pipfile
> +setup-lambda = "python ./setup/awslambda.py"
What's this?

2020-08-13 20:33 UTC, afeld commented on custodian/README.md
> +credits: https://github.com/jtroberts83/Cloud-Custodian/blob/master/schema_expander/schema_quick_ref.txt
Uhh, let's just link out to this rather than copying it in.

2020-08-13 20:33 UTC, afeld commented on custodian/README.md
> +A repo containing rule sets for cloud-custodian inside GSA AWS accounts. This repo does not contain cloud-custodian itself.
```suggestion
A repo containing rule sets for cloud-custodian inside TTS AWS accounts. This repo does not contain cloud-custodian itself.
```

2020-08-13 20:34 UTC, afeld commented on custodian/README.md
> +see `/policies/compliance` for rules that verify compliance (i.e. users w/ console access have MFA enabled, resources are tag appropriate, check that encryption/backups are configured)
This doesn't appear to be accurate.

2020-08-13 20:35 UTC, afeld commented on custodian/README.md
> +## Use Cases
Let's keep the README for _current_ use cases and put the hypotheticals in issues.

2020-08-13 20:35 UTC, afeld commented on custodian/README.md
> +Here you can see the configuration in how we use SQS to send to directly to SLACK. This actually sends the content of the "resources.json.gz" file directly into a slack channel. This option requires
Are we actually doing this?

2020-08-13 20:36 UTC, afeld commented on custodian/README.md
> +$ virtualenv --python=python2 custodian
Should it be Python 3?

2020-08-13 20:36 UTC, afeld commented on custodian/README.md
> +## Concepts
Can we link to the official docs for this?

2020-08-13 20:37 UTC, afeld commented on custodian/inventory/README.md
> +### Missing ?
Missing from the inventory in general? How is this list derived?

2020-08-24 18:05 UTC, JJediny commented
Slightly disagree that the README needs to be in sync with the code, it was included to also account for roadmapping and to document what can be added. Alternatively  we could switch to vendoring the setup to the GSA GRACE module and just add our rulesets too https://github.com/GSA/grace-cloudcustodian

2020-08-24 18:15 UTC, afeld commented on custodian/README.md
> +## Use Cases
…or at the very least, clarify that these are hypotheticals.

2020-08-24 18:16 UTC, afeld commented
> we could switch to vendoring the setup to the GSA GRACE module and just add our rulesets

Defer to your judgement. Suggest doing the smallest thing possible to get something working and mergeable.

2020-09-22 23:41 UTC, afeld requested changes
Nudge on the other open comments as well.

2020-09-22 23:41 UTC, afeld commented on terraform/account_setup/main.tf
> +        "AWS": "arn:aws:iam::133032889584:root"
Can we pass this account number in rather than hard-coding it?

2020-09-22 23:41 UTC, afeld commented on custodian/inventory/dynamodb.yml
> +  - name: dynamodb-table-filter-policy
If we're just going to focus on EC2 and RDS for now, can we delete the inventory files for the other services? We can add them back later if/when we need them.

2020-09-22 23:41 UTC, afeld commented on custodian/accounts-not-working.yml
> +accounts:
This filename implies that you aren't able to connect to these accounts…? Can you say more?

2020-09-23 19:44 UTC, afeld approved these changes
Going to merge this now to do follow-ups with smaller pull requests.

2020-09-23 19:44 UTC, merged